New-AzureResourceGroup `
-Name "MyResourceGroup" `
-Location "West Europe" `
-GalleryTemplateIdentity Microsoft.WebSiteSQLDatabase.0.2.9-preview `
-siteName "webstepdemoweb24" `
-hostingPlanName "MyHostingPlan" `
-siteLocation "West Europe" `
-serverName "webstepdemodb24" `
-serverLocation "West Europe" `
-administratorLogin "Davlind" `
-administratorLoginPassword (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force) `
-databaseName "MyDbName" `
-Verbose
